[theme]

# Primary accent for interactive elements
primaryColor = '#0e4529'

# Background color for the main content area
backgroundColor = '#DFF4EB'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#86D4B8'

# Color used for almost all text
textColor = '#1F134D'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"